version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
      timezone: "Europe/Tallinn"
      time: "10:00"
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
      timezone: "Europe/Tallinn"
      time: "10:00"
